version: '3'

volumes:
  data:
    driver: local

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true" # Enable WebSocket notifications.
      DOMAIN: $VW_DOMAIN
      SMTP_HOST: $SMTP_HOST
      SMTP_FROM: $SMTP_USERNAME
      SMTP_PORT: $SMTP_PORT
      SMTP_SECURITY: "starttls"
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
      ADMIN_TOKEN: $VW_ADMIN_TOKEN
    volumes:
      - data:/data
    ports:
      - "3012:3012"
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=web, websecure
      - traefik.http.routers.vaultwarden.rule=(Host(`$PROXY_EXT_HOST`) && !Path(`/admin`)) || Host(`$PROXY_LAN_HOST`)
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=myresolver
      - traefik.http.routers.vaultwarden.middlewares=authelia@docker
    networks:
      - traefik_proxy