version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: "true" # Enable WebSocket notifications.
      DOMAIN: "${VW_DOMAIN}"
      SMTP_HOST: "ssl0.ovh.net"
      SMTP_FROM: "${SMTP_USERNAME}"
      SMTP_PORT: "587"
      SMTP_SECURITY: "starttls"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      ADMIN_TOKEN: "${VW_ADMIN_TOKEN}"
    volumes:
      - "/media/raid/vaultwarden/data:/data"
    ports:
      - "7677:80"
      - "3012:3012"
    networks:
      - nginx-net
networks:
  nginx-net:
    name: proxynet
    external: true
