version: "3"

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  jellyfin-config:
  tx-config:
  tx-watch:

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: "unless-stopped"
    networks:
      - traefik_proxy
    environment:
      - TZ=Europe/Paris
    ports:
      # - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - tx-config:/config
      - torrent-downloads:/downloads
      - tx-watch:/watch
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.transmission-ui.loadbalancer.server.port=9091
      # Router
      - traefik.http.routers.transmission.entrypoints=web, websecure
      - traefik.http.routers.transmission.rule=Host(`$PROXY_TRANSMISSION_LAN_HOST`)
      - traefik.http.routers.transmission.tls=true
      - traefik.http.routers.transmission.tls.certresolver=myresolver
      - traefik.http.routers.transmission.service=transmission-ui
      - traefik.http.routers.transmission.middlewares=authelia@docker

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: "unless-stopped"
    networks:
      - traefik_proxy
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    # ports:
      # - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.radarr-ui.loadbalancer.server.port=7878
      # Router
      - traefik.http.routers.radarr.entrypoints=web, websecure
      - traefik.http.routers.radarr.rule=Host(`$PROXY_RADARR_LAN_HOST`)
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=myresolver
      - traefik.http.routers.radarr.service=radarr-ui
      - traefik.http.routers.radarr.middlewares=authelia@docker

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    # ports:
      # - 8989:8989
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.sonarr-ui.loadbalancer.server.port=8989
      # Router
      - traefik.http.routers.sonarr.entrypoints=web, websecure
      - traefik.http.routers.sonarr.rule=Host(`$PROXY_SONARR_LAN_HOST`)
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=myresolver
      - traefik.http.routers.sonarr.service=sonarr-ui
      - traefik.http.routers.sonarr.middlewares=authelia@docker

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=Europe/Paris
    # ports:
      # - 9117:9117
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.jackett-ui.loadbalancer.server.port=9117
      # Router
      - traefik.http.routers.jackett.entrypoints=web, websecure
      - traefik.http.routers.jackett.rule=Host(`$PROXY_JACKETT_LAN_HOST`)
      - traefik.http.routers.jackett.tls=true
      - traefik.http.routers.jackett.tls.certresolver=myresolver
      - traefik.http.routers.jackett.service=jackett-ui
      - traefik.http.routers.jackett.middlewares=authelia@docker

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.flaresolverr-svc.loadbalancer.server.port=8191
      # Router
      - traefik.http.routers.flaresolverr.entrypoints=web, websecure
      - traefik.http.routers.flaresolverr.rule=Host(`$PROXY_FLARESOLVERR_LAN_HOST`)
      - traefik.http.routers.flaresolverr.tls=true
      - traefik.http.routers.flaresolverr.tls.certresolver=myresolver
      - traefik.http.routers.flaresolverr.service=flaresolverr-svc

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=Europe/Paris
    ports:
      # - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.jellyfin-ui.loadbalancer.server.port=8096
      # Router
      - traefik.http.routers.jellyfin.entrypoints=web, websecure
      - traefik.http.routers.jellyfin.rule=Host(`$PROXY_JELLYFIN_EXT_HOST`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=myresolver
      - traefik.http.routers.jellyfin.service=jellyfin-ui
