version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '6578:81' # Admin Web Port 
    volumes:
      - /media/raid/nginx/data:/data
      - /media/raid/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-net
networks:
  nginx-net:
    name: proxynet
    external: true
