version: '3.5'

volumes:
  database:
    driver: local
  originals:
    driver: local
  storage:
    driver: local

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

services:
  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:latest
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_USER: $PHOTOPRISM_ADMIN_USER
      PHOTOPRISM_ADMIN_PASSWORD: $PHOTOPRISM_ADMIN_PASSWORD
      PHOTOPRISM_AUTH_MODE: "public"
      PHOTOPRISM_SITE_URL: $PHOTOPRISM_SITE_URL
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"           # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_VECTORS: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"           # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: $MARIADB_USER          # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: $MARIADB_PASSWORD  # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                  # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                       # meta site author
    working_dir: "/photoprism"                         # do not change or remove
    volumes:
      - "originals:/photoprism/originals"  # Original media files (DO NOT REMOVE)
      - "storage:/photoprism/storage"      # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      # Services
      - traefik.http.services.photoprism-ui.loadbalancer.server.port=2342
      # Routers
      - traefik.http.routers.photoprism.entrypoints=web, websecure
      - traefik.http.routers.photoprism.rule=Host(`$PROXY_EXT_HOST`)
      - traefik.http.routers.photoprism.tls=true
      - traefik.http.routers.photoprism.tls.certresolver=myresolver
      - traefik.http.routers.photoprism.service=photoprism-ui
      - traefik.http.routers.photoprism.middlewares=authelia@docker

  mariadb:
    container_name: photoprism_db
    image: mariadb:10.11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "database:/var/lib/mysql" # DO NOT REMOVE
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    networks:
      - traefik_proxy